server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/gateway/auth/**
          filters:
            - StripPrefix=1
        - id: catalog-service
          uri: lb://CATALOG-SERVICE
          predicates:
            - Path=/gateway/catalog/**
          filters:
            - StripPrefix=1
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/gateway/orders/**
          filters:
            - StripPrefix=1
        - id: admin-service
          uri: lb://ADMIN-SERVICE
          predicates:
            - Path=/gateway/admin/**
          filters:
            - StripPrefix=1

jwt:
  secret: ${JWT_SECRET:c2hvcHNwaGVyZS1zdXBlci1zZWNyZXQta2V5LWZvci1qd3QtbXVzdC1iZS1hdC1sZWFzdC0yNTYtYml0cw==}
